### PR TITLE
Support --taql-where for Measurement Sets in dask-ms convert

### LINKED ISSUE #263: Support taql query when converting from CASA format
This would be a very handy feature. Currently I find myself splitting with CASA and then converting to zarr which is not so friendly to disc space. This can obviously only work when converting from a measurement set. I am not sure if it makes sense to support this for the other formats but it may be nice to also have taql-like selection logic (or some subset thereof) when we eventually have support to convert directly from katdal format

### PR DESCRIPTION
**Pull request by sjperkins**
- Closes #263 

- [x] Tests added / passed

  ```bash
  $ py.test -v -s daskms/tests
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i daskms
  $ flake8 daskms
  $ pycodestyle daskms
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
@miguelcarcamov I think you might find this useful too. It add's a TAQL where clause that filters data from any Measurement Set.

**Comment by landmanbester** [comment]
I tried this on the data I just split and got the following error
```
dask-ms convert 1557433849_sdp_l0.ms -g "FIELD_ID,DATA_DESC_ID,SCAN_NUMBER" -o ms2_primary.zarr --chunks="{row:50000,chan:256}" --format zarr --force  --taql-where "FIELD_ID == 0"
2022-10-14 13:53:15     INFO            Process 1315298: waiting for write-lock on file /home/bester/projects/ESO137/msdir/1557433849_sdp_l0.ms/table.lock
Traceback (most recent call last):
  File "/home/bester/.venv/dms/bin/dask-ms", line 8, in <module>
    sys.exit(main())
  File "/home/bester/software/dask-ms/daskms/apps/entrypoint.py", line 9, in main
    return EntryPoint(sys.argv[1:]).execute()
  File "/home/bester/software/dask-ms/daskms/apps/entrypoint.py", line 33, in execute
    cmd.execute()
  File "/home/bester/software/dask-ms/daskms/apps/convert.py", line 415, in execute
    writes = self.convert_table(self.args)
  File "/home/bester/software/dask-ms/daskms/apps/convert.py", line 453, in convert_table
    datasets = reader(args.input, chunks=args.chunks)
  File "/home/bester/software/dask-ms/daskms/dask_ms.py", line 330, in xds_from_ms
    return xds_from_table(
  File "/home/bester/software/dask-ms/daskms/dask_ms.py", line 291, in xds_from_table
    return DatasetFactory(
  File "/home/bester/software/dask-ms/daskms/reads.py", line 466, in datasets
    datasets = self._group_datasets(table_proxy, groups, exemplar_rows, orders)
  File "/home/bester/software/dask-ms/daskms/reads.py", line 380, in _group_datasets
    group_var_dims = _dataset_variable_factory(
  File "/home/bester/software/dask-ms/daskms/reads.py", line 243, in _dataset_variable_factory
    table_proxy.setmaxcachesize(column, 1).result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bester/software/dask-ms/daskms/table_proxy.py", line 111, in _impl
    table.lock(write=True)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/casacore/tables/table.py", line 726, in lock
    self._lock(write, nattempts)
RuntimeError: Error (Bad file descriptor) when acquiring lock on /home/bester/projects/ESO137/msdir/1557433849_sdp_l0.ms/table.lock
```
Looks like tis works fine for ```xds_from_ms``` though
```
In [1]: from daskms import xds_from_ms

In [2]: xds = xds_from_ms('1557433849_sdp_l0.ms', group_cols=['FIELD_ID','DATA_DESC_ID','SCAN_NUMBER'], taql_where="FIELD_ID==0")

In [3]: len(xds)
Out[3]: 8

In [4]:
```
I also tried doing "ANTENNA1 != ANTENNA2" which fails with the same error.

**Comment by sjperkins** [comment]
This looks like a locking error. Do you have the MS open somewhere else?

**Comment by sjperkins** [comment]
I ran the same command line, but with a different measurement set locally and it succeeded.

**Comment by landmanbester** [comment]
That is strange. I do not have the MS open anywhere. I am pretty certain because I can call compute on the data set I get from opening it with xds_from_ms. I can point you at the MS if you want to poke around. It's on oates as /home/bester/projects/ESO137/msdir/1557433849_sdp_l0.ms

**Comment by sjperkins** [comment]
Works for me on oates with the following installation into a resh 3.8 venv

```bash
$ (dask-ms) sjperkins@oates:/home/bester/projects/ESO137/msdir$ pip install "dask-ms[complete] @ git+https://github.com/ratt-ru/dask-ms.git@support-taql-where-in-dask-ms-convert"
```

**Comment by landmanbester** [comment]
Ok, now it's running for me too (it may be too late on a Friday). I will let it complete and check data validity

**Review by landmanbester — APPROVED** [review]
I have verified data validity. It all looks good to me. Thanks @sjperkins

**Comment by sjperkins** [comment]
> I have verified data validity. It all looks good to me. Thanks @sjperkins

Great!

**Pull request merged**
