### PR TITLE
xds_from_zarr should always open zarr groups in read mode

### LINKED ISSUE #261: Mistakenly attempting to access a subtable as a main table causes weird behaviour
* dask-ms version: master
* Python version: 3.8.10
* Operating System: Ubuntu 20.04 LTS

### Description

While attempting to write some flags back to a dataset @landmanbester ran into a bug which I will endeavour to reproduce here.

### Reproducer
```python
from daskms.experimental.zarr import xds_to_zarr, xds_from_zarr
import xarray
import dask.array as da


if __name__ == "__main__":

    xds = xarray.Dataset({"DUMMY": (("row",), da.ones(1000))})

    writes = xds_to_zarr(xds, "dummy_dir::dummy_subtable")

    da.compute(writes)

    # This will work as expected.
    correct_xds = xds_from_zarr("dummy_dir::dummy_subtable")

    # This will silently return an empty list and somehow add a MAIN entry
    # to dummy_dir/dummy_subtable.
    incorrect_xds = xds_from_zarr("dummy_dir/dummy_subtable")

    # If you run this a second time, it will crash due to the presence of the
    # additional MAIN directory in dummy_dir/dummy_subtable, added by the
    # second xds_from_zarr call.
```

### What should happen

Ideally, `dask-ms` should be able to identify when a user has mistakenly pointed it at an incorrect path. More importantly, calls to `xds_from_zarr` should never be able to write to disk as seems to be the case here (creating a new directory with a .zgroup file).

### PR DESCRIPTION
**Pull request by sjperkins**
- Closes #261 

- [x] Tests added / passed

  ```bash
  $ py.test -v -s daskms/tests
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i daskms
  $ flake8 daskms
  $ pycodestyle daskms
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
@landmanbester @JSKenyon The changes in this PR now cause a consistent failure, and no spurious MAIN tables are created:

```bash
Traceback (most recent call last):
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/fsspec/mapping.py", line 137, in __getitem__
    result = self.fs.cat(k)
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/fsspec/spec.py", line 755, in cat
    return self.cat_file(paths[0], **kwargs)
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/fsspec/spec.py", line 665, in cat_file
    with self.open(path, "rb", **kwargs) as f:
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/fsspec/spec.py", line 1034, in open
    f = self._open(
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/fsspec/implementations/local.py", line 162, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/fsspec/implementations/local.py", line 260, in __init__
    self._open()
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/fsspec/implementations/local.py", line 265, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/simon/code/dask-ms/github/dummy_dir/dummy_subtable/MAIN/.zmetadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/code/dask-ms/daskms/experimental/zarr/__init__.py", line 419, in xds_from_zarr
    table_group = zarr.open_consolidated(store_map, mode="r")
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/zarr/convenience.py", line 1304, in open_consolidated
    meta_store = ConsolidatedStoreClass(store, metadata_key=metadata_key)
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/zarr/storage.py", line 2853, in __init__
    meta = json_loads(self.store[metadata_key])
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/zarr/storage.py", line 717, in __getitem__
    return self._mutable_mapping[key]
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/fsspec/mapping.py", line 141, in __getitem__
    raise KeyError(key)
KeyError: '.zmetadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gh261.py", line 19, in <module>
    incorrect_xds = xds_from_zarr("dummy_dir/dummy_subtable")
  File "/home/simon/code/dask-ms/daskms/experimental/zarr/__init__.py", line 421, in xds_from_zarr
    table_group = zarr.open_group(store_map, mode="r")
  File "/home/simon/.cache/pypoetry/virtualenvs/dask-ms-jCyuTJVk-py3.8/lib/python3.8/site-packages/zarr/hierarchy.py", line 1347, in open_group
    raise GroupNotFoundError(path)
zarr.errors.GroupNotFoundError: group not found at path ''
```

**Comment by landmanbester** [comment]
Seems to have fixed the problem. Thanks @sjperkins

**Comment by sjperkins** [comment]
Thanks for the reproducer @JSKenyon. Merging.

**Comment by JSKenyon** [comment]
Thanks for the quick fix @sjperkins!

**Pull request merged**
