### PR TITLE
Update calver dependencies to use inequalities

### PR DESCRIPTION
**Pull request by sjperkins**
- [x] Tests added / passed

  ```bash
  $ py.test -v -s daskms/tests
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i daskms
  $ flake8 daskms
  $ pycodestyle daskms
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
Test cases pass

**Comment by sjperkins** [comment]
This PR changes dask-ms to install 2024 versions of calver'd software, mostly because they're specified using poetry's [caret](https://python-poetry.org/docs/dependency-specification/#caret-requirements) dependency scheme

This is because a `^2023.X.Y` specifier results in a `>= 2023.X.Y, < 2024.0.0` dependency range. 

OTOH it might be possible to just use [inequality](https://python-poetry.org/docs/dependency-specification/#caret-requirements) requirements and keep the range lower.

But I think we'll need stricter requirements going forward due to task keys on the distributed scheduler changing from strings to tuples, as well as the upcoming integration of dask-expr into dask.

**Review by JSKenyon — APPROVED** [review]

**Comment by JSKenyon** [comment]
One comment is that restricting the versioning to a specific year (calver) makes for weirdly quantised dependencies. I think that an inequality constraint is fine and means that things can change more smoothly. I do agree that there may be trouble on the horizon due to upstream churn.

**Comment by sjperkins** [comment]
OK, I've relaxed the calver dependencies to inequality constraints. In combination with the python version, I think poetry will make sensible choices here.

**Pull request merged**
