### PR TITLE
Identify channel and correlation-like dimensions in non-standard MS columns

### LINKED ISSUE #241: Non-standard MS columns have an auto-generated schema which is not chunked according to logic for standard dimensions
* dask-ms version: 0.2.11
* Python version: 3.8
* Operating System: Ubuntu 20.04

### Description

I am trying to convert an MS to zarr chunked by row and channel and its falling over with ```ValueError: Codec does not support buffers of > 2147483647 bytes``` despite the chunks only containing 25000 rows and 128 channels (around 25 MB by my count). Somewhat weirdly I think the error is mostly harmless because it does produce a dataset that I can subsequently read. I have not checked if all the subtables are what they should be though.

### What I Did
 
Here is the full output from convert
```
$ dask-ms convert ms1_primary.ms -g "FIELD_ID,DATA_DESC_ID,SCAN_NUMBER" -o ms1_primary.zarr --chunks="{row:25000,chan:128}" --format zarr --force
2022-08-04 11:05:59,954 - dask-ms - WARNING - Ignoring 'FLAG_CATEGORY': Unable to infer shape of column 'FLAG_CATEGORY' due to:
'Table DataManager error: Invalid operation: TSM: no array in row 0 of column FLAG_CATEGORY in /home/bester/projects/ESO137/msdir/ms1_primary.ms/table.f18'
2022-08-04 11:06:00,178 - dask-ms - WARNING - Ignoring 'FLAG_CATEGORY': Unable to infer shape of column 'FLAG_CATEGORY' due to:
'Table DataManager error: Invalid operation: TSM: no array in row 98332 of column FLAG_CATEGORY in /home/bester/projects/ESO137/msdir/ms1_primary.ms/table.f18'
2022-08-04 11:06:00,657 - dask-ms - WARNING - Ignoring 'FLAG_CATEGORY': Unable to infer shape of column 'FLAG_CATEGORY' due to:
'Table DataManager error: Invalid operation: TSM: no array in row 196664 of column FLAG_CATEGORY in /home/bester/projects/ESO137/msdir/ms1_primary.ms/table.f18'
2022-08-04 11:06:01,007 - dask-ms - WARNING - Ignoring 'FLAG_CATEGORY': Unable to infer shape of column 'FLAG_CATEGORY' due to:
'Table DataManager error: Invalid operation: TSM: no array in row 294996 of column FLAG_CATEGORY in /home/bester/projects/ESO137/msdir/ms1_primary.ms/table.f18'
2022-08-04 11:06:01,196 - dask-ms - WARNING - Ignoring 'FLAG_CATEGORY': Unable to infer shape of column 'FLAG_CATEGORY' due to:
'Table DataManager error: Invalid operation: TSM: no array in row 393328 of column FLAG_CATEGORY in /home/bester/projects/ESO137/msdir/ms1_primary.ms/table.f18'
2022-08-04 11:06:01,395 - dask-ms - WARNING - Ignoring 'FLAG_CATEGORY': Unable to infer shape of column 'FLAG_CATEGORY' due to:
'Table DataManager error: Invalid operation: TSM: no array in row 491660 of column FLAG_CATEGORY in /home/bester/projects/ESO137/msdir/ms1_primary.ms/table.f18'
2022-08-04 11:06:01,625 - dask-ms - WARNING - Ignoring 'FLAG_CATEGORY': Unable to infer shape of column 'FLAG_CATEGORY' due to:
'Table DataManager error: Invalid operation: TSM: no array in row 589992 of column FLAG_CATEGORY in /home/bester/projects/ESO137/msdir/ms1_primary.ms/table.f18'
2022-08-04 11:06:01,838 - dask-ms - WARNING - Ignoring 'FLAG_CATEGORY': Unable to infer shape of column 'FLAG_CATEGORY' due to:
'Table DataManager error: Invalid operation: TSM: no array in row 688324 of column FLAG_CATEGORY in /home/bester/projects/ESO137/msdir/ms1_primary.ms/table.f18'
2022-08-04 11:06:02,008 - dask-ms - INFO - Input: 'measurementset' file:///home/bester/projects/ESO137/msdir/ms1_primary.ms
2022-08-04 11:06:02,008 - dask-ms - INFO - Output: 'zarr' file:///home/bester/projects/ESO137/msdir/ms1_primary.zarr
2022-08-04 11:06:09,797 - dask-ms - WARNING - Ignoring SOURCE
2022-08-04 11:06:09,802 - dask-ms - WARNING - Ignoring 'DIRECTION': Unable to infer shape of column 'DIRECTION' due to:
'TableProxy::getCell: no such row'
2022-08-04 11:06:09,803 - dask-ms - WARNING - Ignoring 'TARGET': Unable to infer shape of column 'TARGET' due to:
'TableProxy::getCell: no such row'
> /home/bester/software/dask-ms/daskms/apps/convert.py(354)execute()
-> dask.compute(writes)
(Pdb) c
Traceback (most recent call last):
  File "/home/bester/.venv/dms/bin/dask-ms", line 33, in <module>
    sys.exit(load_entry_point('dask-ms', 'console_scripts', 'dask-ms')())
  File "/home/bester/software/dask-ms/daskms/apps/entrypoint.py", line 9, in main
    return EntryPoint(sys.argv[1:]).execute()
  File "/home/bester/software/dask-ms/daskms/apps/entrypoint.py", line 32, in execute
    cmd.execute()
  File "/home/bester/software/dask-ms/daskms/apps/convert.py", line 354, in execute
    dask.compute(writes)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/dask/base.py", line 598, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/dask/threaded.py", line 89, in get
   results = get_async(
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/bester/software/dask-ms/daskms/experimental/zarr/__init__.py", line 187, in zarr_setter
    zarray[selection] = data
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/zarr/core.py", line 1353, in __setitem__
    self.set_basic_selection(pure_selection, value, fields=fields)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/zarr/core.py", line 1448, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/zarr/core.py", line 1748, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/zarr/core.py", line 1800, in _set_selection
    self._chunk_setitem(chunk_coords, chunk_selection, chunk_value, fields=fields)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/zarr/core.py", line 2062, in _chunk_setitem
    self._chunk_setitem_nosync(chunk_coords, chunk_selection, value,
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/zarr/core.py", line 2073, in _chunk_setitem_nosync
    self.chunk_store[ckey] = self._encode_chunk(cdata)
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/zarr/core.py", line 2194, in _encode_chunk
    cdata = self._compressor.encode(chunk)
  File "numcodecs/blosc.pyx", line 557, in numcodecs.blosc.Blosc.encode
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/numcodecs/compat.py", line 155, in ensure_contiguous_ndarray
    ensure_contiguous_ndarray_like(
  File "/home/bester/.venv/dms/lib/python3.8/site-packages/numcodecs/compat.py", line 121, in ensure_contiguous_ndarray_like
    raise ValueError(msg)
ValueError: Codec does not support buffers of > 2147483647 bytes
```
But I can still read the main table
```
Python 3.8.13 (default, Apr 19 2022, 00:53:22)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from daskms import xds_from_storage_ms

In [2]: xds = xds_from_storage_ms('ms1_primary.zarr/')

In [3]: d = xds[0].DATA.values

In [4]: d.shape
Out[4]: (98332, 4096, 4)
```
so I am not sure what is happening here.

### LINKED ISSUE #268: Silently fails when providing incorrect schema for WEIGHT column
* dask-ms version: 0.2.14
* Python version: 3.8
* Operating System: Ubuntu20.04

### Description

I just noticed that xds_from_ms silently fails to add the WEIGHT column to the dataset if the provided schema does not contain a tuple for 'dims'. Strangely, it also overwrites the dimension names of known columns like FLAG and DATA, regardless of whether 'dims' is a tuple or not. Seems to work as expected if not providing a schema.

### What I Did

Running 
```
from daskms import xds_from_ms
schema = {}
schema['WEIGHT'] = {'dims': ('corr')}  # note the mistake here, 'dims' should be a tuple
xds = xds_from_ms('path/to/data.ms', columns=('DATA','WEIGHT','FLAG'), chunks={'row':-1, 'chan':8}, table_schema=schema)
```
will produce
```
In [38]: xds
Out[38]:
[<xarray.Dataset>
 Dimensions:  (row: 758160, FLAG-1: 32, FLAG-2: 4, DATA-1: 32, DATA-2: 4)
 Coordinates:
     ROWID    (row) int32 dask.array<chunksize=(758160,), meta=np.ndarray>
 Dimensions without coordinates: row, FLAG-1, FLAG-2, DATA-1, DATA-2
 Data variables:
     FLAG     (row, FLAG-1, FLAG-2) bool dask.array<chunksize=(758160, 32, 4), meta=np.ndarray>
     DATA     (row, DATA-1, DATA-2) complex64 dask.array<chunksize=(758160, 32, 4), meta=np.ndarray>
 Attributes:
     __daskms_partition_schema__:  (('FIELD_ID', 'int32'), ('DATA_DESC_ID', 'i...
     FIELD_ID:                     0
     DATA_DESC_ID:                 0]
```
Note the dimension names of DATA and FLAG. When giving schema a tuple for 'dims' i.e.
```
schema['WEIGHT'] = {'dims': ('corr',)}
xds = xds_from_ms('path/to/data.ms', columns=('DATA','WEIGHT','FLAG'), chunks={'row':-1, 'chan':8}, table_schema=schema)
```
we get
```
In [41]: xds
Out[41]:
[<xarray.Dataset>
 Dimensions:  (row: 758160, FLAG-1: 32, FLAG-2: 4, corr: 4, DATA-1: 32, DATA-2: 4)
 Coordinates:
     ROWID    (row) int32 dask.array<chunksize=(758160,), meta=np.ndarray>
 Dimensions without coordinates: row, FLAG-1, FLAG-2, corr, DATA-1, DATA-2
 Data variables:
     FLAG     (row, FLAG-1, FLAG-2) bool dask.array<chunksize=(758160, 32, 4), meta=np.ndarray>
     WEIGHT   (row, corr) float32 dask.array<chunksize=(758160, 4), meta=np.ndarray>
     DATA     (row, DATA-1, DATA-2) complex64 dask.array<chunksize=(758160, 32, 4), meta=np.ndarray>
 Attributes:
     __daskms_partition_schema__:  (('FIELD_ID', 'int32'), ('DATA_DESC_ID', 'i...
     FIELD_ID:                     0
     DATA_DESC_ID:                 0]
```
Now WEIGHT is there but DATA and FLAG still have the wrong dimension names. If no schema is given, we get
```
In [43]: xds
Out[43]:
[<xarray.Dataset>
 Dimensions:  (row: 758160, chan: 32, corr: 4)
 Coordinates:
     ROWID    (row) int32 dask.array<chunksize=(758160,), meta=np.ndarray>
 Dimensions without coordinates: row, chan, corr
 Data variables:
     FLAG     (row, chan, corr) bool dask.array<chunksize=(758160, 8, 4), meta=np.ndarray>
     WEIGHT   (row, corr) float32 dask.array<chunksize=(758160, 4), meta=np.ndarray>
     DATA     (row, chan, corr) complex64 dask.array<chunksize=(758160, 8, 4), meta=np.ndarray>
 Attributes:
     __daskms_partition_schema__:  (('FIELD_ID', 'int32'), ('DATA_DESC_ID', 'i...
     FIELD_ID:                     0
     DATA_DESC_ID:                 0]
```
which has everything as expected. This is fairly low priority but I thought I would report it anyway. dask-ms should either throw an error if 'dims' is not a tuple or just convert it to a tuple. Either way, the dimension names of known columns should not be altered.

### PR DESCRIPTION
**Pull request by sjperkins**
- Closes #241 
- Closes #268 

- [x] Tests added / passed

  ```bash
  $ py.test -v -s daskms/tests
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i daskms
  $ flake8 daskms
  $ pycodestyle daskms
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

### CODE REVIEW

**Comment by sjperkins** [comment]
I also want to to try address #268 in this PR.

**Comment by landmanbester** [comment]
I'm gonna rerun a convert command that used to fail to confirm that the fix works but it looks pretty uncontroversial to me. I'll get back to you as soon as the convert is done

**Review by JSKenyon — APPROVED** [review]
Looks good! Am correct in saying that this doesn't store this information - it simply presumes that any non-standard column will probably be visibility shaped? This will work in 99.99% of cases, but if the sizes of `chan` and `corr` are the same it may fail/assign `(row, chan, chan)`.

**Comment by sjperkins** [comment]
> Looks good! Am correct in saying that this doesn't store this information - it simply presumes that any non-standard column will probably be visibility shaped? This will work in 99.99% of cases, but if the sizes of `chan` and `corr` are the same it may fail/assign `(row, chan, chan)`.

Its slightly more intelligent than that, it checks if the dimension name is something like `{varname}-{d}` where `varname` is the variable name and `d` is the dimension number. Then it checks if it matches `chan` or `corr`.

**Comment by sjperkins** [comment]
> Looks good! Am correct in saying that this doesn't store this information - it simply presumes that any non-standard column will probably be visibility shaped? This will work in 99.99% of cases, but if the sizes of `chan` and `corr` are the same it may fail/assign `(row, chan, chan)`.

Yep, I think this should try to handle the `chan == corr` case by prioritising chan, and then corr.

**Comment by JSKenyon** [comment]
One extra note - this doesn't work if you only select the column with unknown dimensions:
```python
print(xds_from_ms("msdir/C147_minimal.MS", columns=("TEST_DATA",))[0])
```
prints
```
<xarray.Dataset> Size: 3GB
Dimensions:    (row: 1374420, TEST_DATA-1: 64, TEST_DATA-2: 4)
Coordinates:
    ROWID      (row) int32 5MB dask.array<chunksize=(10000,), meta=np.ndarray>
Dimensions without coordinates: row, TEST_DATA-1, TEST_DATA-2
Data variables:
    TEST_DATA  (row, TEST_DATA-1, TEST_DATA-2) complex64 3GB dask.array<chunksize=(10000, 64, 4), meta=np.ndarray>
Attributes:
    __daskms_partition_schema__:  (('FIELD_ID', 'int32'), ('DATA_DESC_ID', 'i...
    FIELD_ID:                     0
    DATA_DESC_ID:                 0
```

**Comment by sjperkins** [comment]
> One extra note - this doesn't work if you only select the column with unknown dimensions:

Yes. Unfortunately due to the fact that dask-ms was designed to handle arbitrary tables produced by the CTDS, it doesn't really reason about the MS structure very deeply -- so the returned datasets will only have `chan` or `corr` dimensions if standard columns are read to provide this information.

Is this a critical blocker to your current workflows or could this be left to a future PR? I'd imagine that dask-ms convert should work with this change as it bulk exports MS columns.

**Comment by JSKenyon** [comment]
> Is this a critical blocker to your current workflows or could this be left to a future PR? I'd imagine that dask-ms convert should work with this change as it bulk exports MS columns.

Not really, as the schema option still exists (QC always used it for extra model/weight columns). As you say, this should be good enough on the convert. Just thought it worth mentioning as it was the first thing I stumbled over when trying out the branch.

**Comment by landmanbester** [comment]
> Is this a critical blocker to your current workflows or could this be left to a future PR? I'd imagine that dask-ms convert should work with this change as it bulk exports MS columns.

This will work perfectly almost every time. Thanks @sjperkins

**Pull request merged**
